#ifndef GTENUMS_H
#define GTENUMS_H

typedef enum {
    NO_ROIS = 0,
    MANUAL_LABELED_ROIS,
    MANUAL_UNLABELED_ROIS,
    AUTOMATIC_LABELED_ROIS,
    AUTOMATIC_UNLABELED_ROIS,
    REVIEW_FRAME_ROIS    
} RoiLabelsStatus;

typedef enum {	
	COPY_TO_SUMSAMPLED_FRAMES = 0,
	COPY_TO_PARENT_FRAMES,	
	COPY_TO_NEXT_PARENT_FRAME,
	COPY_TO_NEXT_FRAME,
	COPY_UNTIL_LAST_FRAME
} RoiCopyOption;

#endif